// Sitemap index — dynamically wraps all sub-sitemaps generated by app/sitemap.ts
// Fixes: Google Search Console "Couldn't fetch" for /sitemap.xml
// Next.js 14.2.x doesn't auto-generate this index, so we serve it manually.
// SEGMENT_COUNT must match the SEGMENTS array length in app/sitemap.ts

export const dynamic = 'force-dynamic'

// Mirrors the SEGMENTS array in app/sitemap.ts — update both together if adding new sections
const SEGMENT_COUNT = 6 // ['core', 'blog', 'academy', 'help', 'content', 'countries']

export function GET() {
  const base = 'https://askbiz.co'
  const now = new Date().toISOString()

  const sitemaps = Array.from({ length: SEGMENT_COUNT }, (_, i) =>
    `  <sitemap>\n    <loc>${base}/sitemap/${i}.xml</loc>\n    <lastmod>${now}</lastmod>\n  </sitemap>`
  ).join('\n')

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${sitemaps}
</sitemapindex>`

  return new Response(xml, {
    headers: {
      'Content-Type': 'application/xml',
      'Cache-Control': 'public, max-age=3600, s-maxage=3600',
    },
  })
}
