export interface Integration {
  slug: string
  name: string
  category: string
  icon: string
  color: string
  description: string
  longDescription: string
  metaDescription: string
  whatYouGet: string[]
  setupSteps: string[]
  metrics: string[]
  popular: boolean
}

export const INTEGRATIONS: Integration[] = [
  {
    slug: 'shopify',
    name: 'Shopify',
    category: 'eCommerce',
    icon: '🛒',
    color: '#96bf48',
    description: 'Connect your Shopify store and see revenue, orders, products, customers, and refunds — automatically.',
    longDescription: 'The AskBiz Shopify integration syncs your orders, products, customers, and inventory in real time. Within minutes of connecting, you\'ll see your revenue trend, best-selling products, refund rate, average order value, and customer lifetime value — without building a single report.',
    metaDescription: 'Connect Shopify to AskBiz — sync orders, products, customers, and inventory. Track revenue, margin, refund rate, and AOV automatically.',
    whatYouGet: [
      'Real-time revenue and order count dashboard',
      'Product performance: revenue, units, refund rate per SKU',
      'Customer analytics: new vs returning, LTV, repeat rate',
      'Inventory alerts: low stock and overstock detection',
      'Refund and return rate tracking',
      'Daily briefing with your Shopify highlights',
    ],
    setupSteps: [
      'Click "Add integration" and select Shopify',
      'Enter your Shopify store URL',
      'Authorise AskBiz in the Shopify app permissions screen',
      'Your data syncs automatically — first results in under 2 minutes',
    ],
    metrics: ['Revenue', 'Orders', 'AOV', 'Refund rate', 'LTV', 'Inventory turnover'],
    popular: true,
  },
  {
    slug: 'amazon',
    name: 'Amazon Seller Central',
    category: 'eCommerce',
    icon: '📦',
    color: '#ff9900',
    description: 'Connect Amazon Seller Central to track sales, BSR, advertising spend, and FBA inventory across all your markets.',
    longDescription: 'AskBiz pulls your Amazon sales data, ad spend, FBA inventory levels, and bestseller rank — giving you a clear picture of your Amazon performance without logging into Seller Central every day.',
    metaDescription: 'Connect Amazon Seller Central to AskBiz — track sales, BSR, advertising ACOS, and FBA inventory automatically across all your Amazon markets.',
    whatYouGet: [
      'Sales by ASIN, category, and marketplace',
      'Amazon Advertising: spend, ACOS, ROAS by campaign',
      'FBA inventory levels and restock alerts',
      'Bestseller rank tracking for key ASINs',
      'Returns and refunds by ASIN',
      'Multi-marketplace performance comparison',
    ],
    setupSteps: [
      'Select Amazon Seller Central from the integrations list',
      'Log into Seller Central and authorise AskBiz access',
      'Select which marketplaces to sync (UK, US, EU, etc.)',
      'Data syncs daily — advertising data updates every 12 hours',
    ],
    metrics: ['Sales revenue', 'ACOS', 'ROAS', 'BSR', 'FBA stock', 'Return rate'],
    popular: true,
  },
  {
    slug: 'xero',
    name: 'Xero',
    category: 'Accounting',
    icon: '💼',
    color: '#13b5ea',
    description: 'Connect Xero to see your P&L, cash position, outstanding invoices, and key financial ratios — updated daily.',
    longDescription: 'The AskBiz Xero integration pulls your profit and loss, balance sheet, cash flow, accounts receivable, and accounts payable — translating your accounting data into actionable insights for business owners, not accountants.',
    metaDescription: 'Connect Xero to AskBiz — see your P&L, cash position, outstanding invoices, and gross margin automatically updated every day.',
    whatYouGet: [
      'Daily P&L summary: revenue, gross margin, net profit',
      'Cash position and 30/60/90-day cash flow forecast',
      'Overdue invoices and debtor aging report',
      'Gross margin by product or service line',
      'Expense tracking and cost trend alerts',
      'VAT liability and payment schedule',
    ],
    setupSteps: [
      'Select Xero from the integrations list',
      'Log into your Xero account and authorise AskBiz',
      'Select the Xero organisation to connect',
      'Your financial data syncs overnight — P&L visible the next morning',
    ],
    metrics: ['Gross margin', 'Net profit', 'Cash position', 'Debtors', 'Creditors', 'VAT'],
    popular: true,
  },
  {
    slug: 'quickbooks',
    name: 'QuickBooks',
    category: 'Accounting',
    icon: '🧮',
    color: '#2ca01c',
    description: 'Connect QuickBooks Online to track your financials, invoice status, and cash flow — without logging into QuickBooks every day.',
    longDescription: 'AskBiz integrates with QuickBooks Online to pull your income, expenses, invoices, and cash flow data — giving you a plain-English view of your financial health updated daily.',
    metaDescription: 'Connect QuickBooks Online to AskBiz — track revenue, expenses, cash flow, and outstanding invoices automatically. No accounting knowledge required.',
    whatYouGet: [
      'Revenue and expense summary: this week, this month, this year',
      'Outstanding invoices by customer and age',
      'Cash flow forecast based on receivables and payables',
      'Profit and loss by class or location',
      'Expense category breakdown and trend alerts',
      'Tax liability estimates',
    ],
    setupSteps: [
      'Select QuickBooks Online from the integrations list',
      'Sign in with your Intuit account',
      'Authorise AskBiz to read your QuickBooks data',
      'Financial data syncs daily from that point forward',
    ],
    metrics: ['Revenue', 'Expenses', 'Net income', 'Cash flow', 'AR aging', 'Tax liability'],
    popular: false,
  },
  {
    slug: 'stripe',
    name: 'Stripe',
    category: 'Payments',
    icon: '💳',
    color: '#635bff',
    description: 'Connect Stripe to track MRR, churn, payment volume, and failed payments — the essential SaaS and eCommerce metrics.',
    longDescription: 'AskBiz connects to Stripe to give you a real-time view of your payment volume, subscription metrics (MRR, churn, expansion), refund rates, and failed payment recovery — automatically calculated from your Stripe data.',
    metaDescription: 'Connect Stripe to AskBiz — track MRR, churn, payment volume, and refund rates automatically. Essential for SaaS and subscription businesses.',
    whatYouGet: [
      'MRR and ARR calculated from your active subscriptions',
      'Churn rate: logo churn and revenue churn',
      'Expansion MRR from upgrades and additional seats',
      'Failed payment rate and recovery rate',
      'Payment volume by product and plan',
      'Refund and dispute rate tracking',
    ],
    setupSteps: [
      'Select Stripe from the integrations list',
      'Enter your Stripe API key (read-only)',
      'AskBiz imports your subscription and payment history',
      'Metrics calculated immediately — MRR visible within minutes',
    ],
    metrics: ['MRR', 'ARR', 'Churn rate', 'Expansion MRR', 'Failed payments', 'Refund rate'],
    popular: true,
  },
  {
    slug: 'google-sheets',
    name: 'Google Sheets',
    category: 'Spreadsheets',
    icon: '📊',
    color: '#34a853',
    description: 'Connect any Google Sheet to AskBiz and turn your spreadsheet data into live dashboards and AI-powered insights.',
    longDescription: 'If your data lives in Google Sheets — whether it\'s a manual sales tracker, a custom inventory sheet, or a financial model — AskBiz can connect directly and surface insights from it, updated automatically whenever your sheet changes.',
    metaDescription: 'Connect Google Sheets to AskBiz — turn your spreadsheet data into live dashboards and AI-powered insights automatically.',
    whatYouGet: [
      'Live sync from your Google Sheet to AskBiz dashboards',
      'AI analysis of trends and anomalies in your sheet data',
      'Alerts when values in your sheet cross thresholds',
      'Combine Sheet data with other integrations (Shopify, Xero, etc.)',
      'Natural language questions answered from your sheet data',
    ],
    setupSteps: [
      'Select Google Sheets from the integrations list',
      'Sign in with your Google account',
      'Select the spreadsheet and sheet tab to connect',
      'Map your columns — AskBiz guides you through in 2 minutes',
    ],
    metrics: ['Any metric in your sheet', 'Trends', 'Anomalies', 'Custom KPIs'],
    popular: false,
  },
  {
    slug: 'meta-ads',
    name: 'Meta Ads',
    category: 'Advertising',
    icon: '📣',
    color: '#0081fb',
    description: 'Connect Meta Ads (Facebook and Instagram) to track ad spend, ROAS, CPM, CPC, and conversion performance by campaign.',
    longDescription: 'AskBiz integrates with Meta Ads Manager to give you a clear view of your Facebook and Instagram advertising performance — spend, impressions, clicks, conversions, ROAS — broken down by campaign, ad set, and creative.',
    metaDescription: 'Connect Meta Ads to AskBiz — track Facebook and Instagram ad spend, ROAS, CPC, and conversions by campaign automatically.',
    whatYouGet: [
      'Ad spend, impressions, clicks, and conversions by campaign',
      'ROAS and CPA by campaign and ad set',
      'CPM and CPC trend tracking',
      'Budget pacing alerts — know when campaigns are over- or under-spending',
      'Creative performance comparison',
      'Attribution window analysis',
    ],
    setupSteps: [
      'Select Meta Ads from the integrations list',
      'Connect your Facebook Business account',
      'Select the ad accounts to sync',
      'Data syncs every 6 hours — yesterday\'s performance visible each morning',
    ],
    metrics: ['Ad spend', 'ROAS', 'CPA', 'CPM', 'CPC', 'Conversions'],
    popular: true,
  },
  {
    slug: 'google-ads',
    name: 'Google Ads',
    category: 'Advertising',
    icon: '🔍',
    color: '#4285f4',
    description: 'Connect Google Ads to track search, shopping, and display campaign performance — spend, ROAS, CPC, and conversion data.',
    longDescription: 'AskBiz connects to Google Ads to pull your campaign performance data — spend, impressions, clicks, conversions, and ROAS — broken down by campaign type and keyword. See your true advertising ROI and get alerted when performance drops.',
    metaDescription: 'Connect Google Ads to AskBiz — track search and shopping campaign spend, ROAS, CPC, and conversions automatically.',
    whatYouGet: [
      'Spend, impressions, clicks, and conversions by campaign',
      'ROAS and CPA by campaign and keyword',
      'Quality Score tracking for key keywords',
      'Search impression share and lost impression share',
      'Shopping campaign performance by product',
      'Budget utilisation and pacing alerts',
    ],
    setupSteps: [
      'Select Google Ads from the integrations list',
      'Sign in with your Google account',
      'Select the Google Ads account to connect',
      'Data syncs daily — campaign performance visible each morning',
    ],
    metrics: ['Ad spend', 'ROAS', 'CPC', 'Quality Score', 'Impression share', 'Conversions'],
    popular: false,
  },
  {
    slug: 'ebay',
    name: 'eBay',
    category: 'eCommerce',
    icon: '🏷️',
    color: '#e53238',
    description: 'Connect your eBay seller account to track sales, fees, top-selling listings, and account health — alongside your other channels.',
    longDescription: 'AskBiz connects to eBay Seller Hub to pull your sales data, listing performance, seller fees, and account health — giving you a view of your eBay business alongside Shopify, Amazon, and your other channels.',
    metaDescription: 'Connect eBay to AskBiz — track sales, fees, listing performance, and seller account health alongside your other selling channels.',
    whatYouGet: [
      'Sales revenue and order count by period',
      'Top-selling listings by revenue and margin',
      'eBay fees and true net revenue after fees',
      'Seller account health metrics',
      'Returns and defect rate tracking',
      'Multi-channel comparison with Shopify and Amazon',
    ],
    setupSteps: [
      'Select eBay from the integrations list',
      'Log into your eBay account and authorise AskBiz',
      'Select the seller account to sync',
      'Sales data syncs daily',
    ],
    metrics: ['Sales revenue', 'Net after fees', 'Defect rate', 'Return rate', 'Top listings'],
    popular: false,
  },
  {
    slug: 'woocommerce',
    name: 'WooCommerce',
    category: 'eCommerce',
    icon: '🛍️',
    color: '#7f54b3',
    description: 'Connect your WooCommerce store to track orders, revenue, products, and customer data — the same way AskBiz works with Shopify.',
    longDescription: 'AskBiz connects to your WooCommerce store via API to pull orders, product performance, customer data, and refunds — giving you the same automatic insight you\'d get from Shopify, built for WooCommerce stores.',
    metaDescription: 'Connect WooCommerce to AskBiz — track orders, revenue, product performance, and customer LTV automatically from your WordPress store.',
    whatYouGet: [
      'Revenue and order count dashboard',
      'Product performance: sales, refunds, and margin per SKU',
      'Customer analytics: new vs returning, AOV, LTV',
      'Coupon and discount usage tracking',
      'Refund and return rate by product',
      'Daily briefing with your WooCommerce highlights',
    ],
    setupSteps: [
      'Select WooCommerce from the integrations list',
      'Enter your WooCommerce store URL',
      'Generate a WooCommerce REST API key and enter it in AskBiz',
      'Data syncs immediately',
    ],
    metrics: ['Revenue', 'Orders', 'AOV', 'Refund rate', 'LTV', 'Coupon usage'],
    popular: false,
  },
  {
    slug: 'klaviyo',
    name: 'Klaviyo',
    category: 'Email Marketing',
    icon: '📧',
    color: '#09090b',
    description: 'Connect Klaviyo to track email revenue, open rates, click rates, list growth, and flow performance.',
    longDescription: 'AskBiz integrates with Klaviyo to pull your email and SMS campaign performance, flow analytics, and attributed revenue — so you can see which emails are driving sales and which lists are growing.',
    metaDescription: 'Connect Klaviyo to AskBiz — track email revenue, open rates, click rates, and flow performance automatically.',
    whatYouGet: [
      'Attributed revenue from email and SMS campaigns',
      'Open rate, click rate, and unsubscribe rate by campaign',
      'Flow performance: revenue, conversion rate per flow',
      'List growth rate and deliverability metrics',
      'Email revenue as a percentage of total revenue',
      'Best-performing campaigns and subject line analysis',
    ],
    setupSteps: [
      'Select Klaviyo from the integrations list',
      'Enter your Klaviyo Private API key',
      'AskBiz imports your campaign and flow history',
      'Data updates every 24 hours',
    ],
    metrics: ['Email revenue', 'Open rate', 'Click rate', 'Flow revenue', 'List growth'],
    popular: false,
  },
  {
    slug: 'tiktok-ads',
    name: 'TikTok Ads',
    category: 'Advertising',
    icon: '🎵',
    color: '#010101',
    description: 'Connect TikTok Ads Manager to track spend, CPM, video views, conversion rate, and ROAS from your TikTok campaigns.',
    longDescription: 'AskBiz connects to TikTok Ads Manager to give you visibility into your TikTok advertising performance — spend, reach, video metrics, conversion events, and ROAS — alongside your other ad channels.',
    metaDescription: 'Connect TikTok Ads to AskBiz — track ad spend, ROAS, video views, and conversion performance from TikTok Ads Manager automatically.',
    whatYouGet: [
      'Ad spend, reach, and impressions by campaign',
      'Video view metrics: 2s, 6s, and completion rate',
      'Conversion events and CPA by campaign',
      'ROAS and CPM tracking',
      'TikTok vs other channel ROAS comparison',
      'Creative performance by video',
    ],
    setupSteps: [
      'Select TikTok Ads from the integrations list',
      'Connect your TikTok Ads account',
      'Select the ad account to sync',
      'Data syncs every 12 hours',
    ],
    metrics: ['Ad spend', 'ROAS', 'CPM', 'Video completion rate', 'Conversions', 'CPA'],
    popular: false,
  },
]

export const INTEGRATION_CATEGORIES = [
  { slug: 'ecommerce', label: 'eCommerce', icon: '🛒' },
  { slug: 'accounting', label: 'Accounting', icon: '💰' },
  { slug: 'payments', label: 'Payments', icon: '💳' },
  { slug: 'advertising', label: 'Advertising', icon: '📣' },
  { slug: 'email-marketing', label: 'Email Marketing', icon: '📧' },
  { slug: 'spreadsheets', label: 'Spreadsheets', icon: '📊' },
]

export function getIntegration(slug: string): Integration | undefined {
  return INTEGRATIONS.find(i => i.slug === slug)
}
